<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="dieukhoangiaodich.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
    Điều khoản giao dịch
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="body" Runat="Server">
    <style type="text/css">
        .auto-style21 {
            height: 40px;
            color: #FF0000;
            text-align:center;
        }
        .auto-style22 {
            font-size: x-large;
        }
    </style>
     <div class="main">

    <table style="width:100%;">
        <tr>
            <td class="auto-style21"><strong><span class="auto-style22">ĐIỀU KHOẢN GIAO DỊCH</span></strong></td>
        </tr>
        <tr>
            <td>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Chào mừng quý khách đến với CG<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Chúng tôi là Công ty TNHH CJ CG Vietnam, địa chỉ trụ sở chính tại Tòa nhà CJ, Tầng 10-11, 2Bis-4-6 đường Lê Thánh Tôn, Quận 1, Thành phố Hồ Chí Minh.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Khi quý khách truy cập vào trang web của CG có nghĩa là quý khách đồng ý với các điều khoản này. Trang web có quyền thay đổi, chỉnh sửa, thêm hoặc lược bỏ bất kỳ phần nào trong Quy định và Điều kiện sử dụng, vào bất cứ lúc nào. Các thay đổi có hiệu lực ngay khi được đăng trên trang web mà không cần thông báo trước. Và khi quý khách tiếp tục sử dụng trang web, sau khi các thay đổi về Quy định và Điều kiện được đăng tải, có nghĩa là quý khách chấp nhận với những thay đổi đó. Quý khách vui lòng kiểm tra thường xuyên để cập nhật những thay đổi của CG.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Xin vui lòng đọc kỹ trước khi quyết định Đặt Vé trực tuyến.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">1. Phạm Vi Áp Dụng<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Điều kiện dưới đây áp dụng riêng cho chức năng mua vé trực tuyến tại Website. Khi sử dụng chức năng để đặt chỗ và mua vé, Quý khách mặc nhiên đã chấp thuận và tuân thủ tất cả các chỉ dẫn, điều khoản, điều kiện và lưu ý đăng tải trên Website, bao gồm nhưng không giới hạn bởi Điều kiện Sử dụng nêu ở đây. Nếu Quý khách không có ý định mua vé trực tuyến hay không đồng ý với bất kỳ điều khoản hay điều kiện nào nêu trong Điều kiện Sử dụng, xin hãy DỪNG VIỆC SỬ DỤNG chức năng này.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">2. Điều kiện sử dụng tính năng mua vé trực tuyến<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Quý khách phải đăng ký tài khoản với thông tin xác thực về bản thân và phải cập nhật nếu có bất kỳ thay đổi nào. Mỗi người truy cập phải có trách nhiệm với mật khẩu, tài khoản và hoạt động của mình trên web. Hơn nữa, quý khách phải thông báo cho chúng tôi biết khi tài khoản bị truy cập trái phép. Chúng tôi không chịu bất kỳ trách nhiệm nào, dù trực tiếp hay gián tiếp, đối với những thiệt hại hoặc mất mát gây ra do quý khách không tuân thủ quy định.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">3. Quy định về đặt vé trực tuyến<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Tính năng đặt vé trực tuyến hiện chỉ áp dụng cho thành viên của CG. Vui lòng tham khảo thông tin đăng ký thành viên trên website&nbsp;<a href="https://www.cgv.vn/" target="_blank"><span style="color: #E71A0F; text-decoration: none; text-underline: none">www.cg.vn</span></a>.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Thông thường, CG mở bán vé trực tuyến trước ngày chiếu phim, tuy nhiên điều này phụ thuộc vào mỗi phim, mỗi rạp. Nếu suất chiếu bạn muốn đặt chưa được hiển thị trên website vào thời điểm khách đặt vé, xin vui lòng quay lại sau, hoặc liên hệ tới số hot line của CG 1900 6017 để biết thêm thông tin chi tiết.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Thời gian đóng chức năng mua vé trực tuyến là 30 phút trước giờ chiếu phim hoặc khi suất chiếu đã được bán hết vé. Sau thời gian này quý khách có thể đến liên hệ trực tiếp tại rạp để mua vé.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- CG không cam kết giữ chỗ ngồi cho quý khách cho đến khi quý khách hoàn tất thanh toán cho đơn hàng của mình.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Khách hàng có thể đặt chỗ cho tối đa 8 khách (không bao gồm vé trẻ em) trong mỗi lần thực hiện.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Khi tiến hành các bước thanh toán, cần đọc kĩ các thông tin trên màn hình về rạp chiếu phim, tên phim, suất chiếu, và chỗ ngồi trước khi hoàn tất việc xác nhận tất cả các thông tin về vé.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Quý khách thanh toán giao dịch đặt vé theo quy định tại Chính Sách Thanh Toán đăng tải trên CG trước khi nhận mã đặt vé của giao dịch đó. Khi quý khách nhấn (click) vào ô “Thanh toán” để tiến hành thanh toán Đặt chỗ có nghĩa là đã xác nhận rà soát thông tin Đặt chỗ; và đồng ý là Điều Khoản Và Điều Kiện sẽ được áp dụng cho giao dịch mua vé trong giao dịch đó.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Email và tin nhắn xác nhận đặt vé sau khi hoàn thành việc thanh toán vé trực tuyến, quý khách sẽ nhận được thư xác nhận thông tin chi tiết vé đã thanh toán thông qua địa chỉ thư điện tử (email) mà quý khách đã cung cấp. Email xác nhận thông tin đặt vé có thể đi vào hộp thư rác (spam mail) của bạn, vì vậy hãy kiểm tra chúng trước khi liên lạc với CG.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Bằng việc thanh toán qua website này, quý khách chấp nhận vị trí ghế ngồi mà bạn đã đặt. Quý khách đồng ý rằng, trong những trường hợp có sự thay đổi về chương trình phim hoặc bất khả kháng, CG có quyền hoàn trả lại bất kỳ vé nào từ việc mua bán qua trang web này hoặc thực hiện việc chuyển vé cho bạn qua suất chiếu khác theo yêu cầu của quý khách.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Trong suốt quá trình đăng ký, quý khách đồng ý nhận email quảng cáo từ website. Sau đó, nếu không muốn tiếp tục nhận mail, quý khách có thể từ chối bằng cách nhấp vào đường link ở dưới cùng trong mọi email quảng cáo.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">4. Giá Vé<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Giá vé được niêm yết tại CG là giá bán cuối cùng đã bao gồm thuế Giá trị gia tăng (VAT). Giá vé có thể thay đổi tùy thời điểm và chương trình khuyến mãi kèm theo và sẽ được hiển thị rõ tại trang Thanh toán khi quý khách tiến hành đặt hàng.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Giá vé khi đặt vé trực tuyến trên website CG là giá vé người lớn. Các loại vé như học sinh-sinh viên, vé trẻ em và người cao tuổi vui lòng mua trực tiếp tại quầy vé tại các rạp CG Cinemas.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Căn cứ Thông tư số 12/2015/TT-BVHTTDL của Bộ trưởng Bộ Văn hóa, Thể thao và Du lịch có hiệu lực thi hành từ ngày 01/01/2017, Tiêu chí phân loại phim theo lứa tuổi được quy định như sau:<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">1.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o P: Phim được phép phổ biến rộng rãi đến mọi đối tượng<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">2.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C13: Phim cấm phổ biến đến khán giả dưới 13 tuổi<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">3.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C16: Phim cấm phổ biến đến khán giả dưới 16 tuổi<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">4.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C18: Phim cấm phổ biến đến khán giả dưới 18 tuổi<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Khán giả khi xem phim thuộc các phân loại trên vui lòng mang theo giấy tờ tùy thân hoặc hình ảnh của giấy tờ tùy thân có ảnh nhận diện và ngày tháng năm sinh để đảm bảo việc tuân thủ theo quy định.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">1.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C13: Thẻ học sinh, thẻ bảo hiểm, thẻ thư viện, Hộ chiếu… còn hiệu lực<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">2.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C16: CMND, Thẻ học sinh , Hộ chiếu, Thẻ thư viện,… còn hiệu lực<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">3.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o C18: CMND, Thẻ HSSV, Bằng lái xe, Hộ chiếu,… còn hiệu lực<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Khách hàng vui lòng chứng thực được độ tuổi phù hợp với phim được phân loại như trên. CG có quyền từ chối việc bán vé hoặc vào phòng chiếu nếu khách hàng không tuân thủ đúng theo quy định.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">5. Giá trị giao dịch và hình thức thanh toán<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- CG cung cấp các hình thức thanh toán: thẻ Thanh toán Quốc tế hoặc thẻ Thanh toán Nội địa, thẻ quà Tặng CG, CG Voucher và bằng điểm thưởng thành viên.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Trừ một số trường hợp có ghi chú riêng, thông thường quý khách có thể lựa chọn một trong các hình thức thanh toán trên khi tiến hành đặt vé.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- CG có quyền từ chối chấp nhận cho Khách Hàng thanh toán bằng thẻ tín dụng trong một số trường hợp theo quyết định của CG.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Để đảm bảo an toàn thanh toán, Khách Hàng lưu ý:<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">1.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Chỉ thực hiện thanh toán trực tuyến tại cửa sổ liên kết từ CG chuyển đến;<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">2.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Sử dụng và bảo quản thẻ (thẻ tín dụng, thẻ ATM, thẻ mua hàng…) và thông tin tài khoản/thông tin thẻ cẩn thận;<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">3.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Không cho người khác mượn hoặc sử dụng thẻ thành viên để mua vé tại CG. Ngay khi phát hiện giao dịch phát sinh bất thường nào tại CG, Khách Hàng cần liên hệ ngay với bộ phận chăm sóc Khách Hàng của CG để được xử lý kịp thời;<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">4.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Trong mọi trường hợp, với thẻ tín dụng/ghi nợ quốc tế, Khách Hàng vui lòng không để lộ số CVV/CVC/CSC (là mã số bảo mật, bộ ba kí tự số được in ở mặt sau của thẻ) để bảo mật thông tin thẻ;<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">5.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Kiểm tra tài khoản ngân hàng của mình thường xuyên để đảm bảo tất cả giao dịch qua thẻ đều nằm trong tầm kiểm soát.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">6. Điểm thưởng và đổi điểm<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Quy định về tích lũy và quy đổi điểm thưởng được thực hiện theo chính sách cụ thể của CG tại từng thời điểm.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- CG khuyến khích Khách Hàng đăng ký tài khoản thành viên trên CG để tiện theo dõi lịch sử giao dịch, nhận thông tin cập nhật về hàng hóa, các chương trình khuyến mại, hưởng các ưu đãi đối với khách hàng thân thiết…<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">7. Giao kết giao dịch tại CG<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Khách hàng khi mua vé trực tuyến tại website CG phải đăng nhập tài khoản thành viên CG và thực hiện các thao tác theo trình tự sau:<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">1.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Bước 1: Khách hàng lựa chọn suất chiếu theo phim hoặc suất chiếu theo rạp.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">2.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Bước 2: Khách hàng lựa chọn chỗ ngồi.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">3.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Bước 3: Thanh toán bằng các hình thức thanh toán online qua thẻ tín dụng (Visa, Master card..), thẻ ATM, điểm thưởng thành viên, Thẻ quà tặng CG, CG Voucher.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">4.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Bước 4: Khách hàng nhận mã đặt chỗ qua tin nhắn SMS và email.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">5.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Bước 5: Khách hàng cung cấp mã đặt vé và các thông tin tài khoản thành viên CG dùng để đặt vé để nhận vé tại rạp. Khách hàng chỉ có thể nhận vé tại rạp đã đặt vé coi phim. Nếu khách hàng không cung cấp được thông tin tài khoản CG và mã đặt vé, CG có quyền từ chối xuất vé.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">8. Thay đổi, hủy bỏ giao dịch đặt vé tại CG<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Hiện tại CG chưa hỗ trợ dịch vụ hủy hoặc thay đổi thông tin vé đã thanh toán thành công.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Hệ thống Đặt vé Online của CG có liên kết với rất nhiều đối tác khác, bao gồm Cổng thanh toán ONEPAY, các ngân hàng nội địa và các Tổ chức tín dụng quốc tế. Việc thanh toán thành công hay không phụ thuộc rất nhiều vào kết nối mạng của quý khách , việc truyền dẫn, nhận và trả tín hiệu của các tổ chức đối tác trên. CG chỉ thực hiện hoàn tiền trong trường hợp khi giao dịch, tài khoản của 
                    quý khách đã bị trừ tiền nhưng hệ thống của chúng tôi không ghi nhận việc đặt vé đó, và quý khách không nhận được xác nhận đặt vé thành công. Khi đó, quý khách vui lòng liên hệ hotline 1900 6017 (từ 8:00 đến 22:00 tất cả các ngày trong tuần) hoặc bạn có thể liên hệ với chúng tôi qua địa chỉ email hoidap@cg.vn để được hỗ trợ.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Sau khi đã xác nhận các thông tin của khách hàng cung cấp về giao dịch không thành công, tùy theo từng loại tài khoản khách hàng sử dụng mà việc hoàn tiền sẽ có thời gian khác nhau:<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">1.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Thẻ ATM (Nội địa): hoàn tiền trong 7 ngày làm việc.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">2.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Thẻ VISA/ MasterCard (Nội địa): hoàn tiền từ 30 đến 45 ngày làm việc.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: Verdana; mso-bidi-font-family: Verdana; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">3.<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">o Thẻ ATM của ngân hàng Vietcombank: hoàn tiền trong vòng 48 giờ làm việc.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">*Lưu ý: Thời gian hoàn tiền không tính các ngày thứ 7, Chủ nhật và Lễ Tết.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <![if !supportLists]><span style="font-size: 10.0pt; mso-bidi-font-size: 10.5pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; color: #636363; mso-fareast-language: VI"><span style="mso-list: Ignore">·<span style="font: 7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">- Trước khi thanh toán vé trực tuyến, chúng tôi khuyên quý khách nên xác nhận lại Tên phim, Độ tuổi, Giờ chiếu và Rạp chiếu của bộ phim muốn xem.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">9. Thương hiệu và bản quyền<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Mọi quyền sở hữu trí tuệ (đã đăng ký hoặc chưa đăng ký), nội dung thông tin và tất cả các thiết kế, văn bản, đồ họa, phần mềm, hình ảnh, video, âm nhạc, âm thanh, biên dịch phần mềm, mã nguồn và phần mềm cơ bản đều là tài sản của CG. Toàn bộ nội dung của trang web được bảo vệ theo pháp luật sở hữu trí tuệ của Việt Nam và các công ước, điều ước quốc tế mà Việt Nam tham gia hoặc là thành viên.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">10. Luật áp dụng và giải quyết tranh chấp<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Các điều kiện, điều khoản và nội dung của trang web này được điều chỉnh và giải thích theo luật pháp Việt Nam. Các tranh chấp phát sinh từ hoặc liên quan đến (các) giao dịch thực hiện tại trang web này sẽ được ưu tiên giải quyết thông qua thương lượng, hòa giải. Trường hợp các bên không tự giải quyết, tranh chấp sẽ được đưa ra xét xử tại Tòa án cấp có thẩm quyền của Việt Nam.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">11. Quy định về bảo mật<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Trang web của chúng tôi coi trọng việc bảo mật thông tin và sử dụng các biện pháp tốt nhất bảo vệ thông tin và việc thanh toán của quý khách. Thông tin của quý khách trong quá trình thanh toán sẽ được mã hóa để đảm bảo an toàn. Sau khi quý khách hoàn thành quá trình đặt hàng, quý khách sẽ thoát khỏi chế độ an toàn.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Quý khách không được sử dụng bất kỳ chương trình, công cụ hay hình thức nào khác để can thiệp vào hệ thống hay làm thay đổi cấu trúc dữ liệu. Trang web cũng nghiêm cấm việc phát tán, truyền bá hay cổ vũ cho bất kỳ hoạt động nào nhằm can thiệp, phá hoại hay xâm nhập vào dữ liệu của hệ thống. Cá nhân hay tổ chức vi phạm sẽ bị tước bỏ mọi quyền lợi cũng như sẽ bị truy tố trước pháp luật nếu cần thiết. Mọi thông tin giao dịch sẽ được bảo mật trừ trường hợp buộc phải cung cấp theo yêu cầu của tòa án, (các) cơ quan có thẩm quyền hoặc theo quy định của pháp luật.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">12. Giải quyết hậu quả do lỗi nhập sai thông tin thương mại tại CG<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Khách hàng có trách nhiệm cung cấp thông tin đầy đủ và chính xác khi tham gia giao dịch tại CG. Trong trường hợp khách hàng nhập sai thông tin tại trang thông tin My CG, CG có quyền từ chối thực hiện giao dịch. Ngoài ra, trong mọi trường hợp, khách hàng đều có quyền đơn phương chấm dứt giao dịch nếu đã thực hiện bằng cách thông báo cho CG qua đường dây nóng 1900 6017<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <b><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">13. Quy định chấm dứt thỏa thuận<o:p></o:p></span></b></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Trong trường hợp có bất kỳ thiệt hại nào phát sinh do việc vi phạm Quy Định sử dụng trang web, chúng tôi có quyền đình chỉ hoặc khóa tài khoản của quý khách vĩnh viễn. Nếu quý khách không hài lòng với trang web hoặc bất kỳ điều khoản, điều kiện, quy tắc, chính sách, hướng dẫn, hoặc cách thức vận hành của CG thì biện pháp khắc phục duy nhất là ngưng sử dụng dịch vụ của chúng tôi.<o:p></o:p></span></p>
                <p class="MsoNormal">
                    <span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI">Xin quý khách lưu ý chỉ mua hàng khi chấp nhận và hiểu rõ những quy định trên. Nếu cần hỗ trợ thêm thông tin, quý khách vui lòng tham khảo tại </span><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #E71A0F; mso-fareast-language: VI"><a href="http://www.cg.vn">www.cg.vn</a></span><span style="font-size: 10.5pt; font-family: &quot;Verdana&quot;,&quot;sans-serif&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #636363; mso-fareast-language: VI"><o:p></o:p></span></p>
                <p class="MsoNormal">
                    <o:p>&nbsp;</o:p></p>
            </td>
        </tr>
        </div>
</asp:Content>

